# This script changes the admin password on Cisco devices with a stronger one
# To use this script first create a Cisco type 9 hashed password on a Cisco device then replace the all the instances of the SBFZnxXXWIi hash in the playbook.

---
- hosts: cisco
  gather_facts: false
  strategy: free
  tasks:

  - name: Check current admin password
    cisco.ios.ios_command:
      commands:
      - show run | include admin
    register: stdout_lines

  - name: Change password and hash type for admin
    block:
      - name: Change password to type 9 hash
        ansible.netcommon.cli_command:
          command: '{{ item }}'
          prompt:
          - This operation will remove all username related configurations with same name.Do you want to continue?
          answer: y
        loop:
        - configure terminal
        - no username admin
        - username admin privilege 15 secret 9 SBFZnxXXWIi
        - enable secret 9 SBFZnxXXWIi
        register: stdout
        failed_when: stdout is search('Invalid encryption')
        changed_when: stdout is search('SBFZnxXXWIi')
        when: stdout_lines is not search('SBFZnxXXWIi')
    rescue:
      - name: Change password to type 5 hash
        ansible.netcommon.cli_command:
          command: '{{ item }}'
        loop:
        - configure terminal
        - username admin privilege 15 secret 5 XqvxDpsYRRQC
        - enable secret 5 XqvxDpsYRRQC
        register: stdout
        failed_when: stdout is search('Invalid encryption')
        changed_when: stdout is search('XqvxDpsYRRQC')
    always:
      - name: copy run start
        cisco.ios.ios_config:
          save_when: modified
        tags:
          - save
