---
- hosts: juniper_routers
  gather_facts: false
  tasks:

  - name: Backup current switch config (junos)
    junipernetworks.junos.junos_config:
      backup: true
    register: backup_junos_location
    when: ansible_network_os == 'junipernetworks.junos.junos'
    tags:
      - backup


  - name: Set SNMPv3 and syslog host
    junipernetworks.junos.junos_config:
      lines:
        - set snmp v3 usm local-engine user orion_snmp_user authentication-sha authentication-password REDACTED
        - set snmp v3 usm local-engine user orion_snmp_user privacy-aes128 privacy-password REDACTED
        - set snmp v3 vacm security-to-group security-model usm security-name orion_snmp_user group orion_group
        - set snmp v3 vacm access group orion_group default-context-prefix security-model usm security-level privacy read-view GLOBAL
        - set snmp v3 vacm access group orion_group default-context-prefix security-model usm security-level privacy notify-view GLOBAL
        - set snmp engine-id use-default-ip-address
        - set snmp view GLOBAL oid internet include
        - set system syslog host 10.100.100.6 any any
        - set snmp client-list snmp 10.100.100.6/32
      check_commit: true
