---
- hosts: home
  gather_facts: false
  tasks:


  - name: Configure new SNMP ACL
    ios_config:
      lines:
        - remark vmware
        - permit 10.10.10.10
        - remark SIEM
        - permit 10.10.10.10
        - remark Netflow
        - permit 10.10.10.10
      parents: ip access-list standard snmp_acl
      before: no ip access-list standard snmp_acl
      match: strict
      replace: block
    when: ansible_network_os == 'ios'
    tags:
      - acl


  - name: Delete old SNMP ACL
    cisco.ios.ios_acls:
      config:
      - afi: ipv4
        acls:
        - name: snmp
          acl_type: standard
      state: deleted
    when: ansible_network_os == 'ios'
    tags:
      - noacl


  - name: Change SNMP to new standard
    block:
      - name: Enable SNMP views, group, user, and server
        ios_config:
          lines:
            - snmp-server view snmp_view iso included
            - snmp-server view snmp_view mib-2 included
            - snmp-server view snmp_view system included
            - snmp-server group orion_group v3 priv write snmp_view access snmp_acl
            - snmp-server user orion_snmp_user orion_group v3 auth sha PASSWORD priv aes 128 SECRET
            - snmp-server host 10.10.10.10 traps version 3 priv orion_snmp_user
            - no snmp-server host 10.10.10.10 REDACTED
            - no snmp-server host 10.10.10.11 REDACTED
            - no snmp-server community REDACTED RW snmp
            - no snmp-server community REDACTED RO snmp
            - no snmp-server community REDACTED RO snmp
            - no snmp-server community REDACTED RO snmp
            - no snmp-server community REDACTED RW snmp
            - no snmp-server host 10.10.10.11 REDACTED
            - no snmp-server host 10.10.10.11 REDACTED
    rescue:
      - name: Rescue if error adding SNMPv3
        ios_config:
          lines:
            - snmp-server community REDACTED RO snmp
            - snmp-server host 10.10.10.10 REDACTED
    tags:
      - snmpv3


  - name: Enable SNMP traps
    cisco.ios.ios_config:
      lines:
        - snmp-server system-shutdown
        - snmp-server enable traps snmp authentication coldstart warmstart
        - snmp-server enable traps config
        - snmp-server enable traps transceiver all
        - snmp-server enable traps cpu threshold
        - snmp-server enable traps envmon fan shutdown supply temperature status
        - snmp-server enable traps errdisable
        - snmp-server enable traps vlancreate
        - snmp-server enable traps vlandelete
        - snmp-server enable traps stackwise
    ignore_errors: True
    tags:
      - traps


  - name: copy run start
    cisco.ios.ios_config:
      save_when: always
    tags:
      - save
